version: "2"
linters:
  enable:
    - misspell
    - unconvert
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - pkg/acme/x
      - third_party$
      - builtin$
      - examples$
    ## TODO: drop Endpoints api
    rules:
      - linters:
          - staticcheck
        text: "SA1019: [a-z0-9]+.Endpoints is deprecated"
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - pkg/acme/x
      - pkg/common
      - pkg/controller/legacy
      - third_party$
      - builtin$
      - examples$
