blank_issues_enabled: true
contact_links:
- name: Slack
  url: https://kubernetes.slack.com/channels/haproxy-ingress
  about: "We're in the #haproxy-ingress channel on Kubernetes Slack. Take an invite at https://slack.k8s.io if not subscribed yet"
- name: Mailing List
  url: https://groups.google.com/forum/#!forum/haproxy-ingress
  about: Ask questions and follow announcements. Post via `haproxy-ingress@googlegroups.com` mail address without being subscribed.
- name: Stack Overflow
  url: https://stackoverflow.com/questions/tagged/haproxy-ingress
  about: Practical questions and curated answers.
